# Generated by Django 6.0.4 on 2026-06-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
