# Generated by Django 6.0.4 on 2026-05-16 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0001_initial"),
        ("employers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=150)),
                ("job_description", models.TextField()),
                (
                    "required_education_level",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("diploma", "Diploma"),
                            ("bachelor", "Bachelor"),
                            ("master", "Master"),
                            ("phd", "PhD"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "required_years_of_experience",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "work_mode",
                    models.CharField(
                        choices=[
                            ("remote", "Remote"),
                            ("onsite", "On-site"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=30,
                    ),
                ),
                ("job_location", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="employers.employerprofile",
                    ),
                ),
                (
                    "required_skills",
                    models.ManyToManyField(blank=True, to="candidates.skill"),
                ),
            ],
        ),
    ]
